<h1>Manage Schedules</h1>
<p>Schedules can be automatically re-generated by clicking the button below</p>

<p>There are <?php echo $number_unsched; ?> shifts still unscheduled</p>
<br><br>
<button class="btn btn-primary btn-large">Generate Schedules</button>


